### ISSUE TITLE
Image(phone svg) overlaps on text

### ISSUE THREAD

**Issue by AbhishekGMV** [Yasir284/Project-10-Interior-design-landing-page#1]
[
![image](https://user-images.githubusercontent.com/43518356/181570132-e44363b3-f65e-4f76-a555-61039b2b8bb3.png)
](url)

**Comment by Yasir284** [comment]
Yes, I will make this website media responsive very soon. Thanks for your feedback.  :)

**Comment by AbhishekGMV** [comment]
Not the responsiveness, website break even in desktop mode. Please check the attached snapshot
